language: r

notifications:
  slack:
    secure: lnO7OWkimtwP3AZImeDuoo8WH39ZNXDX5mCNsVonSZlXgHCTuf4mXK+6RAA1x6EJFmypG3qbWD+6YQuUcLMji4oSN4p3sVSC2Z2Rdz0Ef+4UspFij8oKcYainI2qwG89FYn0CC8ITrh+kxtLbTLF6VYwb5jlZ8DRsAk8LVWxm+g=
